### ISSUE TITLE
Full Keyboard Access 설정 문제

### ISSUE THREAD

**Issue by FourwingsY** [devxoul/allkdic#41]
저는 맥에서도 탭을 통해 선택되는 버튼을 옮겨다니곤 합니다.
자세하게는 이 글을 보시면 좋을 것 같습니다.
http://macnews.tistory.com/471

이 설정이 켜져있지 않다면 올ㅋ사전을 열자마자 바로 텍스트창에 커서가 닿아 즉각적인 검색이 가능하지만
이 설정을 켜 놓은 상태에서는 환경설정 버튼에 키보드 포커싱이 가게 됩니다. 

때문에 마우스로 일부러 텍스트 입력창을 선택해줘야 하는 번거로움이 있습니다.
(사실 이 글을 쓰면서 원인을 발견하기 전까진 버그인줄만 알았습니다;;)
아... 그러고보니 탭 한번으로도 가능하긴 하네요.... (스스로 충격)

여튼, 간단하게 말씀드리자면, Full Keyboard Access 설정이 켜진 상태에서도 텍스트 입력창에 포커싱이 오도록 초큼만 고쳐주셨으면 합니다 :)

p.s. 올ㅋ사전 매우 잘 쓰고 있습니다! 감사합니다!

**Comment by devxoul** [comment]
전혀 생각지도 못했던 곳에서 발생하는 이슈가 있군요. 다음 릴리즈때 이 문제를 해결하도록 하겠습니다.

알려주셔서 감사합니다 :smile:
