### ISSUE TITLE
가로&세로 사이즈 조절, 발음 재생기능

### ISSUE THREAD

**Issue by khs8727** [devxoul/allkdic#43]
아주 좋은 프로그램 만들어 주셔서 감사합니다!
NaverDic 을 오래전부터 사용하고있지만, 앱스토어에서 사라진후 개발자분도 업데이트를 안하시는것 같더라구요.
이번기회에 올ㅋ딕으로 갈아탔는데 아주 맘에 듭니다.

잘 사용하고있지만 다음 기능을 추가해주신다면 더 완벽한 프로그램이 될것 같네요 ^^

1. 창조절 가능 (크기조절 드래깅으로 가능 / 크기 조절 고정 select button) 혹은 (스크린크기 대비 몇%)
2. 영어발음 지원 (지금은 눌러도 실행이 되지 않네요)

=============================================================================

여기에다가 improvement 사항을 올려도 될까해서 올렸다가, 페이스북에 다시한번 올리고 여기 글을 지우려했지만
github이 코멘트 자체를 삭제를 못하게 막아놨네요. 
글 내용을 지웠었는데, 그래도 여기에 댓글달아주시고 한것을 보니 그렇게 용도로 사용하는것 같아서 글 다시 살려놓습니다.
유저들의 개선사항 꼼꼼히 체크해주시고 반영해주시는것 보면서 같은 software engineer로서 기분이 좋습니다.
화이팅 하세요^^

**Comment by devxoul** [comment]
안녕하세요. 제안해주신 기능은 현재 #19(1번) 이슈와 #19(2번) 이슈로 등록되어있습니다. 다음 릴리즈때 포함될 수 있도록 하겠습니다 :D

**Comment by devxoul** [comment]
중복된 이슈(#64)가 있어서 이슈를 종료합니다.
