### ISSUE TITLE
안녕하세요 쓰다보니 또 하나 이슈가 생겨서 올려놓습니다~

### ISSUE THREAD

**Issue by khs8727** [devxoul/allkdic#45]
안녕하세요 수고하십니다 ^^

올ㅋ사전 정말 잘 쓰고 있습니다!
계속 쓰다가 저는 보통 찾을단어를 선택하고 복사한후 올ㅋ사전을 불러서 바로 붙여넣기를 해서 사용하는데요
어쩔땐 복사하기가 제대로 안되는거에요.. 알고보니.. 이게 키보드가 한글상태일때 붙여넣기가 안되네요.
다시 영어상태로 바꾸면 붙여넣기 문제없이 됩니다.

키보드 한/영 에 따라서 붙여넣기가 되고 안되고가 왜그런지 이해가 안되네요 ㅡ0ㅡ;;
업데이트 부탁드립니다~

**Comment by devxoul** [comment]
안녕하세요. https://github.com/devxoul/allkdic/commit/6bc1524e258768b2a37935e5124b8da11f7b3a2a 커밋에서 해당 문제가 해결되었습니다. 조만간 문제가 해결된 버전을 릴리즈하겠습니다!

감사합니다.
