### ISSUE TITLE
발음듣기 기능 - 소리가 안납니다.

### ISSUE THREAD

**Issue by khs8727** [devxoul/allkdic#64]
이제 더이상 업데이트 안해주시는건가요 ㅠ?
다른 기능들은 다 잘 동작하는데, 어느순간부터 발음듣기 기능이 안되네요..
업데이트 해주실수 있으신가요?

감사합니다!

**Comment by devxoul** [comment]
안녕하세요. 네이버 작은창 사전의 발음 듣기 기능은 Flash Player를 사용하여 제공됩니다. Safari를 통해 https://helpx.adobe.com/flash-player.html 링크로 접속하신 뒤, Safari용 Flash Player Plugin을 설치해주세요. 설치가 완료된 후 올ㅋ사전을 종료 후 재실행하면 발음 듣기를 정상적으로 사용하실 수 있습니다.
